version: "3"
services:
  redis:
    container_name: pubsub
    image: redis
    expose:
      - 6379
  app:
    container_name: app
    build: .
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - ${PORT}:${PORT}
